POST {{domain}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "captchaCode": "",
  "captchaUuid": "",
  "loginDevice": 1
}


###  code_generator_query_table_list
POST {{domain}}/support/codeGenerator/queryTableList
Content-Type: application/json
x-access-token: {{token}}

{}

###
GET {{domain}}/support/codeGenerator/queryTableColumn/t_code_generator_config
x-access-token: {{token}}

